root/gift/urls.py
# Internal
from gift.views import *
# Django
from django.urls import path


app_name = 'gift'
urlpatterns = \
[
    path('', helloWorld, name = 'helloWorld'),
    path('items', items, name = 'items'),
    path('item/<int:giftItemId>', item, name = 'item')
]

root/root/urls.py
# Django
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = \
[
    path('gift/', include('gift.urls')),
    path('admin/', admin.site.urls)
]

root/gift/models.py
# Django
from django.db import models


class GiftItem(models.Model):

    name = models.CharField(max_length = 100, verbose_name = "Название элемента")

    purchasePrice = models.FloatField(verbose_name = "Закупочная цена")
    customerPrice = models.FloatField(verbose_name = "Цена для клиента")

    description = models.TextField(verbose_name = "Описание продукта", default = "")


    def __str__(self):
        return "Элемент: {}, Закупочная цена: {}, Цена для клиента: {}; {}".format(self.name,
                                                                                   self.purchasePrice,
                                                                                   self.customerPrice,
                                                                                   self.description)

root/gift/views.py
# Internal
import gift.models as model
# Django
from django.shortcuts import render, get_object_or_404, get_list_or_404

from django.http import HttpResponse


def helloWorld(request):
    return HttpResponse("Hello world.")


def items(request):
    giftItems = get_list_or_404(model.GiftItem)

    context = {'GiftItems': giftItems}
    return render(request, 'gift/items_view.html', context)


def item(request, giftItemId):

    giftItem = get_object_or_404(model.GiftItem, pk = giftItemId)

    context = {'GiftItem': giftItem}
    return render(request, 'gift/item_detail_view.html', context)

root/gift/templates/gift/item_detail_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ GiftItem.name }}
</body>
</html>

root/gift/templates/gift/items_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if GiftItems %}
        <ul>
        {% for GiftItem in GiftItems %}
            <li><a href="{% url 'gift:item' GiftItem.id %}">{{ GiftItem.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>
</html>